In [77]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [78]:
dfsocial=pd.read_csv(r"F:\ML,\Logistic Regression\LR\Social_Network_Ads.csv")

In [79]:
dfsocial.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [80]:
dfsocial.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [81]:
dfsocial.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [82]:
dfsocial=dfsocial.drop(["User ID","Gender"],axis=1)

In [83]:
X=dfsocial.drop("Purchased",axis=1)

In [84]:
X.head(2)

Age  EstimatedSalary
0   19            19000
1   35            20000

In [85]:
y=dfsocial["Purchased"]

In [86]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.20,random_state=0)

In [89]:
Xtrain.shape,Xtest.shape

((320, 2), (80, 2))

In [90]:
ytrain.shape,ytest.shape

((320,), (80,))

In [91]:
from sklearn.preprocessing import StandardScaler

In [92]:
sc=StandardScaler()

In [93]:
Xtrain=sc.fit_transform(Xtrain)

In [94]:
Xtest=sc.fit_transform(Xtest)

In [95]:
Xtrain.shape,Xtest.shape

((320, 2), (80, 2))

In [96]:
ytrain.shape,ytest.shape

((320,), (80,))

In [97]:
from sklearn.linear_model import LogisticRegression

In [98]:
lr=LogisticRegression()

In [99]:
lr.fit(Xtrain,ytrain)

LogisticRegression()

In [100]:
y_pred=lr.predict(Xtest)

In [101]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [102]:
from sklearn.metrics import confusion_matrix

In [103]:
cm=confusion_matrix(ytest,y_pred)

In [104]:
cm

array([[52,  6],
       [ 3, 19]], dtype=int64)

In [105]:
print(cm)

[[52  6]
 [ 3 19]]


In [106]:
from sklearn.metrics import accuracy_score

In [107]:
sc=accuracy_score(ytest,y_pred)

In [108]:
sc

0.8875

In [109]:
print(sc)

0.8875


In [110]:
bias=lr.score(Xtrain,ytrain)

In [111]:
bias

0.821875

In [112]:
variance=lr.score(Xtest,ytest)

In [113]:
variance

0.8875

In [114]:
from sklearn.metrics import classification_report

In [115]:
cr=classification_report(ytest,y_pred)

In [116]:
cr

'              precision    recall  f1-score   support\n\n           0       0.95      0.90      0.92        58\n           1       0.76      0.86      0.81        22\n\n    accuracy                           0.89        80\n   macro avg       0.85      0.88      0.86        80\nweighted avg       0.89      0.89      0.89        80\n'

In [117]:
from matplotlib.colors import ListedColormap
